# Generated by Django 5.0 on 2023-12-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_crud.busstop'),
        ),
    ]
