# Generated by Django 5.0 on 2023-12-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0002_route_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='stop',
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.route')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('booked', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
    ]
