# Generated by Django 5.0 on 2023-12-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0004_busseatstatus_seat_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.route')),
            ],
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
    ]
