# Generated by Django 5.0 on 2023-12-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0005_passengerdetails_delete_busstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.passengerdetails')),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.busseatstatus')),
            ],
        ),
    ]
