# Generated by Django 5.0 on 2023-12-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0007_remove_passengerdetails_route_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busseatstatus',
            options={'ordering': ['seat_side', 'seat_number']},
        ),
    ]
