# Generated by Django 5.0 on 2024-01-02 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0008_alter_busseatstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerseat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
