# Generated by Django 5.0 on 2024-01-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0009_passengerseat_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerseat',
            name='created_at',
        ),
    ]
