# Generated by Django 3.2.10 on 2024-01-05 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0010_remove_passengerseat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerseat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
