# Generated by Django 5.0 on 2024-01-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0011_passengerseat_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='Khalti', max_length=25)),
                ('paid_amount', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('passenger_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_crud.passengerdetails')),
            ],
        ),
    ]
