# Generated by Django 5.0 on 2024-01-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0013_rename_paymentdetail_paymentdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busseatstatus',
            options={'ordering': ['seat_number']},
        ),
        migrations.AlterField(
            model_name='busseatstatus',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
