# Generated by Django 5.0 on 2024-01-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_crud', '0014_alter_busseatstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busseatstatus',
            options={'ordering': ['seat_side', 'seat_number']},
        ),
    ]
